version: '3'

services:
    admin:
        build:
            context: .
        environment:
            - APP_NAME=admin
        ports:
            - "3003:3003"
        env_file:
            - .env
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:3003" ]
            interval: 10s
            retries: 5

    user:
        build:
            context: .
        environment:
            - APP_NAME=user
        env_file:
            - .env
        ports:
            - "3002:3002"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:3002" ]
            interval: 10s
            retries: 5
