export const languages = [
  {
    code: 'en',
    name: 'English',
    description: 'English language',
    content: {
      post_summary: 'New Posts',
      site_summary: 'New Sites',
      trending_summary: 'New Trendings',
      category_summary: 'Categories',
      google_console_summary: 'Google Indexed',
      keyword_summary: 'Keywords',
      source_summary: 'Sources',
      google_Search_status_chart: 'Google Search',

      setting_nav: 'System Setting',

      dashboard_nav: 'Dashboard',
      dashboard_page: 'Dashboard',
      pull_button: 'Pull',
      clone_button: 'Clone',

      category_nav: 'Category',
      category_list_page: 'Category List',
      category_new_button: 'Add New',
      category_slug_item: 'Slug',
      category_name_item: 'Name',
      category_description_item: 'Description',
      category_posts_item: 'Posts',
      category_sites_item: 'Sites',

      user_nav: 'User',
      user_list_page: 'User List',
      user_new_button: 'New User',
      user_detail_page: 'User Detail',
      user_table_title: 'Users',
      user_detail_title: 'User Detail',
      user_profile_title: 'Profile',
      user_tab_profile: 'Profile',
      server_nav: 'Server',
      server_new_button: 'New Server',
      connect_server_button: 'Connect Server',
      server_list_page: 'Server List',
      server_detail_page: 'Server Detail',
      server_detail_title: 'Server Detail',
      server_table_title: 'Servers',
      server_general_tab: 'General',
      server_status_tab: 'Status',
      server_setup_tab: 'Config Container',
      server_item_name: 'Server',
      server_item_host: 'Host',
      server_item_port: 'Port',
      server_item_user: 'User',
      server_item_created_at: 'Created Time',
      server_item_password: 'Password',
      server_inactive_status: 'Inactive',
      server_active_status: 'Active',
      server_connected: 'Connected',
      server_disconnected: 'Disconnected',
      server_used: 'Used',
      server_available: 'Available',
      server_ram: 'Ram',
      server_room: 'Room',
      server_network: 'Network',
      server_disk: 'Disk',
      information_title: 'Information',
      all_service: 'All Services',
      docker_containers: 'Containers Docker',
      docker_images: 'Images Docker',

      site_nav: 'Site',
      site_list_page: 'Site List',
      site_detail_page: 'Site Detail',
      site_table_title: 'Sites',
      site_detail_title: 'Site Detail',
      site_new_button: 'New Site',
      site_domain_item: 'Domain',
      site_name_item: 'Name',
      site_description_item: 'Description',
      site_posts_item: 'Posts',
      site_token_item: 'Token',
      site_auto_post_item: 'Auto Post',
      site_categories_item: 'Categories',
      site_tele_token: 'Telegram Token',
      site_tele_bot_name: 'Telegram Bot Name',
      site_tele_chat_name: 'Telegram Chat Name',
      site_tele_chat_id: 'Telegram Chat Id',
      site_tele_verify: 'Verified',

      site_post_title: 'Post',
      site_request_index: 'Request Index',
      site_indexing: 'Indexing',
      site_created_at_item: 'Created At',

      product_nav: 'Product',
      product_list_page: 'Product List',
      product_detail_page: 'Product Detail',
      product_new_button: 'New Product',
      product_table_title: 'Products',
      product_detail_title: 'Product Detail',

      blog_nav: 'Blog',
      blog_unused_nav: 'Blog Unused',
      blog_all_nav: 'All Blog',
      blog_trending_nav: 'Trending',

      blog_archived_nav: 'Archived',
      blog_list_page: 'Blog List',
      blog_detail_page: 'Blog Detail',
      blog_new_button: 'New Blog',
      blog_table_title: 'Blogs',
      blog_detail_title: 'Blog Detail',
      blog_public_button: 'Public',
      blog_draft_button: 'Draft',
      blog_site_item: 'Sites',
      blog_category_item: 'Categories',

      blog_title_item: 'Title',
      blog_description_item: 'Description',
      blog_keywords_item: 'Keywords',
      blog_content_item: 'Content',

      language_nav: 'Language',
      language_list_page: 'Language List',
      language_table_title: 'Languages',
      language_detail_title: 'Language Detail',
      language_tab_all_label: 'All',
      language_item_content: 'Content',
      language_item_code: 'Code',
      language_item_language: 'Language',

      color_nav: 'Color',

      login_button: 'Log in',
      signup_button: 'Sign up',
      register_button: 'Register',
      logout_button: 'Logout',
      submit_button: 'Submit',
      cancel_button: 'Cancel',
      save_button: 'Save',
      delete_button: 'Delete',
      update_button: 'Update',
      create_button: 'Create',
      detail_button: 'Detail',
      save_changes_button: 'Save Changes',
      need_help_button: 'Need help',

      home_menu: 'Home',
      profile_menu: 'Profile',
      settings_menu: 'Settings',

      create_form_label: 'Quick Add',
      update_form_label: 'Quick Update',
      delete_form_label: 'Quick Delete',
      delete_form_title: 'Are you sure you want to delete?',
      search_item: 'Search',

      signin_title: 'Sign in',
      signin_item_email: 'Email address',
      signin_item_password: 'Password',
      get_started: 'Get started',
      no_account: 'Don’t have an account?',
      remember_me: 'Remember me',
      allready_account: 'Already have an account?',
      forgot_password: 'Forgot password?',

      signup_title: 'Get started absolutely free.',
      signup_description: 'Free forever. No credit card needed.',
      signup_item_user_name: 'User name',
      signup_item_email: 'Email address',
      signup_item_password: 'Password',
      agree_to: 'By registering, I agree to Minimal',
      terms_of_service: 'Terms of Service',
      privacy_policy: 'Privacy Policy',

      filter_list_title: 'Filter list',
      pagination_per_page: 'Rows per page',
      table_number_selected: '{count} selected',

      notification_title: 'Notifications',
      notification_view_all: 'View All',
      notification_new: 'New',
      notification_read_all: 'Mark all as read',
      notification_before_that: 'Before That',
      notification_count: 'You have {count} unread messages',
      notification_tab_all: 'All',
      notification_tab_new: 'Unread',
      notification_tab_archived: 'Archived',

      notify_changed_language: 'Language has been changed!',
      notify_success_api_call: 'API call was successful!',
      notify_success_get_data: 'Data retrieved successfully!',
      notify_success_post_data: 'Request completed successfully!',
      notify_success_update: 'Successfully updated the data!',
      notify_success_delete: 'Data deleted successfully!',
      notify_error_generic: 'An error occurred while fetching data.',
      notify_error_network: 'Network error. Please check your connection.',
      notify_error_server:
        'Unable to reach the server. Please try again later.',
      notify_error_no_results: 'No results found for your request.',
      notify_error_invalid_data: 'Invalid data received from the server.',
      notify_error_missing_data:
        'The response is missing necessary information.',
      notify_error_empty_response: 'Empty response. Please try again.',

      or: 'OR',
      of: 'OF',
      and: 'AND',
      setting_title: 'Settings',
      dark_mode_title: 'Dark Mode',
      light_mode_title: 'Light Mode',
      system_mode_title: 'System Mode',
      contrast_title: 'Contrast',
      preset_title: 'Preset',
      list_title: 'List',
      detail_title: 'Detail',

      docker_container_id_item: 'Id',
      docker_container_name_item: 'Container',
      docker_container_status_item: 'Status',
      docker_container_images_item: 'Image',

      docker_image_id_item: 'Id',
      docker_image_name_item: 'Image',
      docker_image_status_item: 'Status',
      docker_image_tag_item: 'Tag',
      docker_image_created_item: 'Created',
      docker_image_size_item: 'Size',
      docker_image_run: 'Run',
      docker_image_stop: 'Stop',

      docker_container_state_item: 'State',
      docker_container_ports_item: 'Ports',

      repository_id_item: 'Id',
      repository_name_item: 'Name',
      repository_images_item: 'Images',
      repository_github_item: 'Github',
      repository_username_item: 'Username',
      repository_email_item: 'Email',
      repository_fine_grained_token_item: 'Fine Grained Token',
      repository_pull_button: 'Pull Source',
      repository_new_button: 'Add Repository',
      repository_build_button: 'Build',
      repository_list_title: 'Repositories',
      repository_create_title: 'Clone Repository',
      repository_create_description:
        'Clone and create docker-compose.xml (if not exist)',
      repository_update_title: 'Update Basic Information',
      repository_update_description:
        'Pull and create docker-compose.xml (if not exist)',
      repository_server_path_item: 'Path',

      repository_optional_setting: 'Optional Settings',
      repository_basic_information: 'Basic Information',
      repository_env_file: 'Env file',
      repository_env_file_guide: 'system auto create file .env',
      repository_services_title: 'Services',
      repository_environment_title: 'Environment',
      repository_volumes_title: 'Volumes',
      repository_build_env: 'Build with new .env',
      repository_build_docker_compose: 'Build with new docker-compose.yml',

      repository_clone_title: 'Clone Repository',
      repository_clone_description:
        'Clone and create docker-compose.xml, .env (if not exists)',

      repository_pull_title: 'Pull Repository',
      repository_pull_description:
        'Pull new code and replace .env and service in your data.',

      repository_build_title: 'Build a new image',
      repository_build_description:
        'Will replace .env, docker-compose.yml in source (if exist options)',

      repository_run_title: 'Run a new container',
      repository_run_description: '',

      repository_up_title: 'Up',
      repository_up_description: '',

      repository_down_title: 'Down',
      repository_down_description: '',

      nginx_title: 'Nginx Config',
      nginx_add_file_title: 'Add new config',
      nginx_name_file_item: 'File name (.conf)',
      nginx_content_file_item: 'Content',

      server_notify_fetching_data: 'The data is being updated...',
      server_notify_connecting: 'Re-connect to server...',
      server_notify_disconnected: 'Unable to connect to the server.',

      trending_now_title: 'Trending Now',
      trending_title_item: 'Title',
      trending_search_volume_item: 'Search Volume',
      trending_started_item: 'Started',

      google_console_nav: 'Google Console',
      google_sitemap_nav: 'Google Sitemap',
      google_website_nav: 'Google Website',
      google_indexing_nav: 'Google Indexing',
      google_console_list_page: 'Google Console List',
      google_logs_nav: 'Google Logs',

      blog_unsed_description: 'Blogs no longer used on any site',
      blog_archived_description: 'Old blogs not indexed or removed from index',
      blog_trending_description: 'Trending blogs from search data',

      user_email_item: 'Email',
      user_name_item: 'Name',
      user_username_item: 'Username',
      user_password_item: 'Password',
      user_avatar_item: 'Avatar',
      user_banner_item: 'Banner',
      user_site_item: 'Sites',
      user_created_item: 'Created At',
    },
  },
  {
    code: 'vn',
    name: 'Vietnamese',
    description: 'Vietnamese language',
    content: {
      post_summary: 'Bài viết mới',
      site_summary: 'Trang web mới',
      trending_summary: 'Xu hướng mới',
      category_summary: 'Danh mục',
      google_console_summary: 'Đã index trên Google',
      keyword_summary: 'Từ khóa',
      source_summary: 'Nguồn',
      google_Search_status_chart: 'Google Indexing',

      setting_nav: 'Cài đặt hệ thống',

      dashboard_nav: 'Bảng điều khiển',
      dashboard_page: 'Bảng điều khiển',
      pull_button: 'Kéo mã nguồn',
      clone_button: 'Sao chép kho',

      category_nav: 'Danh mục',
      category_list_page: 'Danh sách danh mục',
      category_new_button: 'Thêm mới',
      category_slug_item: 'Slug',
      category_name_item: 'Tên',
      category_description_item: 'Mô tả',
      category_posts_item: 'Bài viết',
      category_sites_item: 'Trang web',

      user_nav: 'Người dùng',
      user_list_page: 'Danh sách người dùng',
      user_new_button: 'Người dùng mới',
      user_detail_page: 'Chi tiết người dùng',
      user_table_title: 'Người dùng',
      user_detail_title: 'Chi tiết người dùng',
      user_profile_title: 'Hồ sơ',
      user_tab_profile: 'Hồ sơ',

      server_nav: 'Máy chủ',
      server_new_button: 'Thêm máy chủ',
      connect_server_button: 'Kết nối máy chủ',
      server_list_page: 'Danh sách máy chủ',
      server_detail_page: 'Chi tiết máy chủ',
      server_detail_title: 'Chi tiết máy chủ',
      server_table_title: 'Máy chủ',
      server_general_tab: 'Tổng quan',
      server_status_tab: 'Trạng thái',
      server_setup_tab: 'Cấu hình container',
      server_item_name: 'Tên máy chủ',
      server_item_host: 'Host',
      server_item_port: 'Cổng',
      server_item_user: 'Người dùng',
      server_item_created_at: 'Thời gian tạo',
      server_item_password: 'Mật khẩu',
      server_inactive_status: 'Không hoạt động',
      server_active_status: 'Đang hoạt động',
      server_connected: 'Đã kết nối',
      server_disconnected: 'Mất kết nối',
      server_used: 'Đang dùng',
      server_available: 'Sẵn sàng',
      server_ram: 'Ram',
      server_room: 'Phòng máy',
      server_network: 'Mạng',
      server_disk: 'Ổ đĩa',
      information_title: 'Thông tin',
      all_service: 'Tất cả dịch vụ',
      docker_containers: 'Docker Containers',
      docker_images: 'Docker Images',

      site_nav: 'Trang web',
      site_list_page: 'Danh sách trang',
      site_detail_page: 'Chi tiết trang',
      site_table_title: 'Trang web',
      site_detail_title: 'Chi tiết trang web',
      site_new_button: 'Thêm trang mới',
      site_domain_item: 'Tên miền',
      site_name_item: 'Tên',
      site_description_item: 'Mô tả',
      site_posts_item: 'Bài viết',
      site_token_item: 'Token',
      site_auto_post_item: 'Tự động đăng bài',
      site_categories_item: 'Danh mục',
      site_tele_token: 'Telegram Token',
      site_tele_bot_name: 'Tên Bot Telegram',
      site_tele_chat_name: 'Tên Chat Telegram',
      site_tele_chat_id: 'ID Chat Telegram',
      site_tele_verify: 'Đã xác minh',

      site_post_title: 'Bài viết',
      site_request_index: 'Yêu cầu index',
      site_indexing: 'Đang index',
      site_created_at_item: 'Ngày tạo',

      product_nav: 'Sản phẩm',
      product_list_page: 'Danh sách sản phẩm',
      product_detail_page: 'Chi tiết sản phẩm',
      product_new_button: 'Thêm sản phẩm',
      product_table_title: 'Sản phẩm',
      product_detail_title: 'Chi tiết sản phẩm',

      blog_nav: 'Blog',
      blog_unused_nav: 'Blog không dùng',
      blog_all_nav: 'Tất cả Blog',
      blog_trending_nav: 'Xu hướng',
      blog_archived_nav: 'Đã lưu trữ',
      blog_list_page: 'Danh sách blog',
      blog_detail_page: 'Chi tiết blog',
      blog_new_button: 'Thêm Blog',
      blog_table_title: 'Blog',
      blog_detail_title: 'Chi tiết blog',
      blog_public_button: 'Công khai',
      blog_draft_button: 'Nháp',
      blog_site_item: 'Trang web',
      blog_category_item: 'Danh mục',

      blog_title_item: 'Tiêu đề',
      blog_description_item: 'Mô tả',
      blog_keywords_item: 'Từ khóa',
      blog_content_item: 'Nội dung',

      language_nav: 'Ngôn ngữ',
      language_list_page: 'Danh sách ngôn ngữ',
      language_table_title: 'Ngôn ngữ',
      language_detail_title: 'Chi tiết ngôn ngữ',
      language_tab_all_label: 'Tất cả',
      language_item_content: 'Nội dung',
      language_item_code: 'Mã',
      language_item_language: 'Ngôn ngữ',

      color_nav: 'Màu sắc',

      login_button: 'Đăng nhập',
      signup_button: 'Đăng ký',
      register_button: 'Đăng ký',
      logout_button: 'Đăng xuất',
      submit_button: 'Gửi',
      cancel_button: 'Hủy',
      save_button: 'Lưu',
      delete_button: 'Xóa',
      update_button: 'Cập nhật',
      create_button: 'Tạo mới',
      detail_button: 'Chi tiết',
      save_changes_button: 'Lưu thay đổi',
      need_help_button: 'Cần trợ giúp',

      home_menu: 'Trang chủ',
      profile_menu: 'Hồ sơ',
      settings_menu: 'Cài đặt',

      create_form_label: 'Thêm nhanh',
      update_form_label: 'Cập nhật nhanh',
      delete_form_label: 'Xóa nhanh',
      delete_form_title: 'Bạn có chắc muốn xóa không?',
      search_item: 'Tìm kiếm',

      signin_title: 'Đăng nhập',
      signin_item_email: 'Email',
      signin_item_password: 'Mật khẩu',
      get_started: 'Bắt đầu ngay',
      no_account: 'Chưa có tài khoản?',
      remember_me: 'Ghi nhớ tôi',
      allready_account: 'Đã có tài khoản?',
      forgot_password: 'Quên mật khẩu?',

      signup_title: 'Bắt đầu miễn phí ngay.',
      signup_description: 'Miễn phí vĩnh viễn. Không cần thẻ tín dụng.',
      signup_item_user_name: 'Tên người dùng',
      signup_item_email: 'Email',
      signup_item_password: 'Mật khẩu',
      agree_to: 'Khi đăng ký, tôi đồng ý với',
      terms_of_service: 'Điều khoản dịch vụ',
      privacy_policy: 'Chính sách bảo mật',

      filter_list_title: 'Bộ lọc danh sách',
      pagination_per_page: 'Số dòng mỗi trang',
      table_number_selected: '{count} mục đã chọn',

      notification_title: 'Thông báo',
      notification_view_all: 'Xem tất cả',
      notification_new: 'Mới',
      notification_read_all: 'Đánh dấu tất cả đã đọc',
      notification_before_that: 'Trước đó',
      notification_count: 'Bạn có {count} thông báo chưa đọc',
      notification_tab_all: 'Tất cả',
      notification_tab_new: 'Chưa đọc',
      notification_tab_archived: 'Lưu trữ',

      notify_changed_language: 'Đã thay đổi ngôn ngữ!',
      notify_success_api_call: 'Gọi API thành công!',
      notify_success_get_data: 'Lấy dữ liệu thành công!',
      notify_success_post_data: 'Yêu cầu thành công!',
      notify_success_update: 'Cập nhật dữ liệu thành công!',
      notify_success_delete: 'Xóa dữ liệu thành công!',
      notify_error_generic: 'Đã xảy ra lỗi khi lấy dữ liệu.',
      notify_error_network: 'Lỗi kết nối mạng. Vui lòng kiểm tra lại.',
      notify_error_server: 'Không thể kết nối máy chủ. Thử lại sau.',
      notify_error_no_results: 'Không tìm thấy kết quả phù hợp.',
      notify_error_invalid_data: 'Dữ liệu không hợp lệ từ máy chủ.',
      notify_error_missing_data: 'Thiếu thông tin cần thiết từ phản hồi.',
      notify_error_empty_response: 'Phản hồi trống. Vui lòng thử lại.',

      or: 'HOẶC',
      of: 'CỦA',
      and: 'VÀ',
      setting_title: 'Cài đặt',
      dark_mode_title: 'Chế độ tối',
      light_mode_title: 'Chế độ sáng',
      system_mode_title: 'Theo hệ thống',
      contrast_title: 'Độ tương phản',
      preset_title: 'Giao diện',
      list_title: 'Danh sách',
      detail_title: 'Chi tiết',

      docker_container_id_item: 'Id',
      docker_container_name_item: 'Tên container',
      docker_container_status_item: 'Trạng thái',
      docker_container_images_item: 'Ảnh',

      docker_image_id_item: 'Id',
      docker_image_name_item: 'Tên ảnh',
      docker_image_status_item: 'Trạng thái',
      docker_image_tag_item: 'Thẻ',
      docker_image_created_item: 'Ngày tạo',
      docker_image_size_item: 'Kích thước',
      docker_image_run: 'Chạy',
      docker_image_stop: 'Dừng',

      docker_container_state_item: 'Trạng thái',
      docker_container_ports_item: 'Cổng',

      repository_id_item: 'Id',
      repository_name_item: 'Tên',
      repository_images_item: 'Ảnh',
      repository_github_item: 'Github',
      repository_username_item: 'Tên đăng nhập',
      repository_email_item: 'Email',
      repository_fine_grained_token_item: 'Fine Grained Token',
      repository_pull_button: 'Kéo mã nguồn',
      repository_new_button: 'Thêm kho',
      repository_build_button: 'Build',
      repository_list_title: 'Kho lưu trữ',
      repository_create_title: 'Sao chép kho',
      repository_create_description:
        'Sao chép và tạo docker-compose.xml (nếu chưa có)',
      repository_update_title: 'Cập nhật thông tin cơ bản',
      repository_update_description:
        'Kéo mã và tạo docker-compose.xml (nếu chưa có)',
      repository_server_path_item: 'Đường dẫn trên máy chủ',

      repository_optional_setting: 'Cài đặt tùy chọn',
      repository_basic_information: 'Thông tin cơ bản',
      repository_env_file: 'File .env',
      repository_env_file_guide: 'Hệ thống sẽ tự tạo file .env',
      repository_services_title: 'Dịch vụ',
      repository_environment_title: 'Môi trường',
      repository_volumes_title: 'Volumes',
      repository_build_env: 'Build với .env mới',
      repository_build_docker_compose: 'Build với docker-compose.yml mới',

      repository_clone_title: 'Sao chép kho',
      repository_clone_description:
        'Sao chép và tạo docker-compose.xml, .env (nếu chưa có)',

      repository_pull_title: 'Kéo kho lưu trữ',
      repository_pull_description:
        'Kéo mã mới và thay thế .env và service hiện tại.',

      repository_build_title: 'Tạo image mới',
      repository_build_description:
        'Sẽ thay thế .env, docker-compose.yml trong source (nếu chọn)',

      repository_run_title: 'Chạy container mới',
      repository_run_description: '',

      repository_up_title: 'Khởi động',
      repository_up_description: '',

      repository_down_title: 'Dừng lại',
      repository_down_description: '',

      nginx_title: 'Cấu hình NGINX',
      nginx_add_file_title: 'Thêm cấu hình mới',
      nginx_name_file_item: 'Tên file (.conf)',
      nginx_content_file_item: 'Nội dung',

      server_notify_fetching_data: 'Đang cập nhật dữ liệu...',
      server_notify_connecting: 'Đang kết nối lại máy chủ...',
      server_notify_disconnected: 'Không thể kết nối tới máy chủ.',

      trending_now_title: 'Xu hướng hiện tại',
      trending_title_item: 'Tiêu đề',
      trending_search_volume_item: 'Lượng tìm kiếm',
      trending_started_item: 'Bắt đầu từ',

      google_console_nav: 'Google Console',
      google_sitemap_nav: 'Google Sitemap',
      google_website_nav: 'Google Website',
      google_indexing_nav: 'Google Indexing',
      google_console_list_page: 'Danh sách Google Console',
      google_logs_nav: 'Google Logs',

      blog_unsed_description: 'Blog không còn được dùng ở bất kỳ site nào',
      blog_archived_description: 'Blog cũ không còn index hoặc đã bị gỡ bỏ',
      blog_trending_description: 'Blog xu hướng từ dữ liệu tìm kiếm',

      user_email_item: 'Email',
      user_name_item: 'Họ & Tên',
      user_username_item: 'Tên Đăng Nhập',
      user_password_item: 'Mật Khẩu',
      user_avatar_item: 'Ảnh đại diện',
      user_banner_item: 'Ảnh bìa',
      user_site_item: 'Sites',
      user_created_item: 'Cập nhất mới nhất',
    },
  },
];
