export const languages = [
  {
    code: 'en',
    name: 'English',
    description: 'English language',
    content: {
      greeting: 'Hello, welcome to our application!',
      farewell: 'Goodbye, see you soon!',
      home: 'Home',
      about: 'About Us',
      contact: 'Contact',
      services: 'Services',
      privacy_policy: 'Privacy Policy',
      terms_of_service: 'Terms of Service',
      login_button: 'Log in',
      signup_button: 'Sign up',
      logout_button: 'Log out',
      submit_button: 'Submit',
      cancel_button: 'Cancel',
      save_button: 'Save',
      delete_button: 'Delete',
      email_label: 'Email',
      password_label: 'Password',
      username_label: 'Username',
      remember_me_label: 'Remember me',
      forgot_password_label: 'Forgot Password?',
      error_invalid_email: 'Invalid email address',
      error_invalid_password: 'Password must be at least 6 characters',
      error_required_field: 'This field is required',
      error_login_failed: 'Login failed, please try again',
      success_registration: 'Registration successful! Please log in.',
      success_update: 'Profile updated successfully!',
      success_password_change: 'Password changed successfully.',
      loading: 'Loading...',
      fetching_data: 'Fetching data...',
      saving_data: 'Saving...',
      profile: 'Profile',
      settings: 'Settings',
      edit_profile: 'Edit Profile',
      change_password: 'Change Password',
      new_message: 'You have a new message.',
      new_notification: 'You have new notifications.',
      mark_as_read: 'Mark as read',
      clear_notifications: 'Clear all notifications',
      access_denied: 'You do not have permission to access this page.',
      unauthorized_user: 'You are not authorized to perform this action.',
      not_found_title: 'Page Not Found',
      not_found_message: "Sorry, the page you're looking for does not exist.",
      server_error_title: 'Something went wrong',
      server_error_message:
        "We're experiencing technical issues. Please try again later.",
      date_format: 'DD/MM/YYYY',
      time_format: 'HH:mm:ss',
      order_number: 'Order Number',
      order_status: 'Order Status',
      order_shipped: 'Shipped',
      order_delivered: 'Delivered',
      cart_empty: 'Your cart is empty.',
      cart_total: 'Total',
      cart_checkout: 'Proceed to Checkout',
    },
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    description: 'Vietnamese language',
    content: {
      greeting: 'Chào bạn, chào mừng đến với ứng dụng của chúng tôi!',
      farewell: 'Tạm biệt, hẹn gặp lại!',
      home: 'Trang chủ',
      about: 'Giới thiệu',
      contact: 'Liên hệ',
      services: 'Dịch vụ',
      privacy_policy: 'Chính sách bảo mật',
      terms_of_service: 'Điều khoản sử dụng',
      login_button: 'Đăng nhập',
      signup_button: 'Đăng ký',
      logout_button: 'Đăng xuất',
      submit_button: 'Gửi',
      cancel_button: 'Hủy',
      save_button: 'Lưu',
      delete_button: 'Xóa',
      email_label: 'Email',
      password_label: 'Mật khẩu',
      username_label: 'Tên người dùng',
      remember_me_label: 'Ghi nhớ tôi',
      forgot_password_label: 'Quên mật khẩu?',
      error_invalid_email: 'Địa chỉ email không hợp lệ',
      error_invalid_password: 'Mật khẩu phải ít nhất 6 ký tự',
      error_required_field: 'Trường này là bắt buộc',
      error_login_failed: 'Đăng nhập thất bại, vui lòng thử lại',
      success_registration: 'Đăng ký thành công! Vui lòng đăng nhập.',
      success_update: 'Cập nhật hồ sơ thành công!',
      success_password_change: 'Mật khẩu đã được thay đổi.',
      loading: 'Đang tải...',
      fetching_data: 'Đang lấy dữ liệu...',
      saving_data: 'Đang lưu...',
      profile: 'Hồ sơ',
      settings: 'Cài đặt',
      edit_profile: 'Chỉnh sửa hồ sơ',
      change_password: 'Thay đổi mật khẩu',
      new_message: 'Bạn có tin nhắn mới.',
      new_notification: 'Bạn có thông báo mới.',
      mark_as_read: 'Đ đánh dấu là đã đọc',
      clear_notifications: 'Xóa tất cả thông báo',
      access_denied: 'Bạn không có quyền truy cập trang này.',
      unauthorized_user: 'Bạn không được phép thực hiện hành động này.',
      not_found_title: 'Trang không tìm thấy',
      not_found_message: 'Xin lỗi, trang bạn đang tìm không tồn tại.',
      server_error_title: 'Đã xảy ra lỗi',
      server_error_message:
        'Chúng tôi đang gặp sự cố kỹ thuật. Vui lòng thử lại sau.',
      date_format: 'DD/MM/YYYY',
      time_format: 'HH:mm:ss',
      order_number: 'Số đơn hàng',
      order_status: 'Trạng thái đơn hàng',
      order_shipped: 'Đã giao hàng',
      order_delivered: 'Đã giao',
      cart_empty: 'Giỏ hàng của bạn trống.',
      cart_total: 'Tổng cộng',
      cart_checkout: 'Tiến hành thanh toán',
    },
  },
];
